### ISSUE TITLE
M-x recenter input line?

### ISSUE THREAD

**Issue by vyp** [jorgenschaefer/circe#308]
I don't like to have to always keep looking at the bottom of the screen/buffer, so I want to be able to do `M-x recenter` on the input (bottom) line. But that doesn't work and the input line is still at the bottom of the buffer, why? And so is there a way to disable this? (And for example though, if I do `M-x recenter` on the second last line, it recenters properly, but going to the input line again, causes everything to put all the way down again. 😕)

Possibly related not sure: https://github.com/jorgenschaefer/circe/issues/14

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Please customize the `lui-scroll-behavior` variable to fit your needs. Does this solve your problem?

**Comment by vyp** [comment]
Yes it does, thank you! I'm sorry I didn't see this.

**Comment by jorgenschaefer** [comment]
Glad this is solved. Please do not hesitate to open new issues if you have further problems, and enjoy Circe! :-)

**Comment by vyp** [comment]
Thank you! Coming from ERC, circe is much easier to use (at least for me). As in, even though I've only been using it for a few days, it can already easily do a lot of things that took me some time to figure out in ERC. However, I still have a few questions which I can't seem to find the answer to anywhere, but it'll probably be better if I open separate issues for them (after I search a bit more). 😁
